#!/bin/bash

firstrun() {
	cp -r /var/lib/mysql/* /data
	chown -R mysql /data
	chown root /data/debian*
}

main() {
	if [[ ! -f /data/debian-5.5.flag ]]
	then
		firstrun
	fi

	echo "datadir=/data" >> /etc/mysql/my.cnf
	echo "wsrep_data_home_dir=/data" >> /etc/mysql/my.cnf
	case "$1" in
		master)
			echo "Starting master"
			echo "wsrep_cluster_address=gcomm://" >> /etc/mysql/my.cnf
			/usr/bin/mysqld_safe
			;;
		node)
			echo "Starting node"
			if [[ -z "$2" ]]
			then
				echo "Missing master node IP"
			else
				echo "wsrep_cluster_address=gcomm://$2" >> /etc/mysql/my.cnf
				/usr/bin/mysqld_safe
			fi
			;;
		*)
			echo "start <master|node> <master node ip>"
	esac
}

main $@

